// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StlExplorerServer.Data;

#nullable disable

namespace StlExplorerServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260315165718_AddCheminDossier")]
    partial class AddCheminDossier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClassLibStlExploServ.Famille", b =>
                {
                    b.Property<int>("FamilleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FamilleID"));

                    b.Property<string>("NomFamille")
                        .HasColumnType("longtext");

                    b.HasKey("FamilleID");

                    b.ToTable("Familles");
                });

            modelBuilder.Entity("ClassLibStlExploServ.Modele", b =>
                {
                    b.Property<int>("ModeleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ModeleID"));

                    b.Property<string>("CheminDossier")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("SujetID")
                        .HasColumnType("int");

                    b.HasKey("ModeleID");

                    b.HasIndex("SujetID");

                    b.ToTable("Modeles");
                });

            modelBuilder.Entity("ClassLibStlExploServ.Sujet", b =>
                {
                    b.Property<int>("SujetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SujetID"));

                    b.Property<int>("FamilleID")
                        .HasColumnType("int");

                    b.Property<string>("NomSujet")
                        .HasColumnType("longtext");

                    b.HasKey("SujetID");

                    b.HasIndex("FamilleID");

                    b.ToTable("Sujets");
                });

            modelBuilder.Entity("ClassLibStlExploServ.Modele", b =>
                {
                    b.HasOne("ClassLibStlExploServ.Sujet", "Sujet")
                        .WithMany("Modeles")
                        .HasForeignKey("SujetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sujet");
                });

            modelBuilder.Entity("ClassLibStlExploServ.Sujet", b =>
                {
                    b.HasOne("ClassLibStlExploServ.Famille", "Famille")
                        .WithMany("Sujets")
                        .HasForeignKey("FamilleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("ClassLibStlExploServ.Famille", b =>
                {
                    b.Navigation("Sujets");
                });

            modelBuilder.Entity("ClassLibStlExploServ.Sujet", b =>
                {
                    b.Navigation("Modeles");
                });
#pragma warning restore 612, 618
        }
    }
}
